puts 'seeding locations...'

locations = [
  { name: 'Abrantes' },
  { name: 'Águeda' },
  { name: 'Aguiar da Beira' },
  { name: 'Alandroal' },
  { name: 'Albergaria-a-Velha' },
  { name: 'Albufeira' },
  { name: 'Alcácer do Sal' },
  { name: 'Alcanena' },
  { name: 'Alcobaça' },
  { name: 'Alcochete' },
  { name: 'Alcoutim' },
  { name: 'Alenquer' },
  { name: 'Alfandega da Fé' },
  { name: 'Alijó' },
  { name: 'Aljezur' },
  { name: 'Aljustrel' },
  { name: 'Almada' },
  { name: 'Almeida' },
  { name: 'Almeirim' },
  { name: 'Almodôvar' },
  { name: 'Alpiarça' },
  { name: 'Alter do Chão' },
  { name: 'Alvaiázere' },
  { name: 'Alvito' },
  { name: 'Amadora' },
  { name: 'Amarante' },
  { name: 'Amares' },
  { name: 'Anadia' },
  { name: 'Angra do Heroismo' },
  { name: 'Ansião' },
  { name: 'Arcos de Valdevez' },
  { name: 'Arganil' },
  { name: 'Armamar' },
  { name: 'Arouca' },
  { name: 'Arraiolos' },
  { name: 'Arronches' },
  { name: 'Arruda dos Vinhos' },
  { name: 'Aveiro' },
  { name: 'Avis' },
  { name: 'Azambuja' },
  { name: 'Baião' },
  { name: 'Barcelos' },
  { name: 'Barrancos' },
  { name: 'Barreiro' },
  { name: 'Batalha' },
  { name: 'Beja' },
  { name: 'Belmonte' },
  { name: 'Benavente' },
  { name: 'Bombarral' },
  { name: 'Borba' },
  { name: 'Boticas' },
  { name: 'Braga' },
  { name: 'Bragança' },
  { name: 'Cabeceiras de Bast' },
  { name: 'Cadaval' },
  { name: 'Caldas da Rainha' },
  { name: 'Calheta' },
  { name: 'Calheta' },
  { name: 'Câmara de Lobos' },
  { name: 'Caminha' },
  { name: 'Campo Maior' },
  { name: 'Cantanhede' },
  { name: 'Carrazeda de Ansiães' },
  { name: 'Carregal do Sal' },
  { name: 'Cartaxo' },
  { name: 'Cascais' },
  { name: 'Castanheira de Pera' },
  { name: 'Castelo Branco' },
  { name: 'Castelo de Paiva' },
  { name: 'Castelo de Vide' },
  { name: 'Castro Daire' },
  { name: 'Castro Marim' },
  { name: 'Castro Verde' },
  { name: 'Celorico da Beira' },
  { name: 'Celorico de Basto' },
  { name: 'Chamusca' },
  { name: 'Chaves' },
  { name: 'Cinfães' },
  { name: 'Coimbra' },
  { name: 'Condeixa-a-Nova' },
  { name: 'Constancia' },
  { name: 'Coruche' },
  { name: 'Corvo' },
  { name: 'Covilhã' },
  { name: 'Crato' },
  { name: 'Cuba' },
  { name: 'Elvas' },
  { name: 'Entroncamento' },
  { name: 'Espinho' },
  { name: 'Esposende' },
  { name: 'Estarreja' },
  { name: 'Estremoz' },
  { name: 'Évora' },
  { name: 'Fafe' },
  { name: 'Faro' },
  { name: 'Felgueiras' },
  { name: 'Ferreira do Alentejo' },
  { name: 'Ferreira do Zêzere' },
  { name: 'Figueira da Foz' },
  { name: 'Figueira de Castelo Rodrigo' },
  { name: 'Figueiró dos Vinhos' },
  { name: 'Fornos de Algodres' },
  { name: 'Freixo de Espada a Cinta' },
  { name: 'Fronteira' },
  { name: 'Funchal' },
  { name: 'Fundão' },
  { name: 'Gavião' },
  { name: 'Góis' },
  { name: 'Golegã' },
  { name: 'Gondomar' },
  { name: 'Gouveia' },
  { name: 'Grandola' },
  { name: 'Guarda' },
  { name: 'Guimarães' },
  { name: 'Horta' },
  { name: 'Idanha-a-Nova' },
  { name: 'Ílhavo' },
  { name: 'Lagoa' },
  { name: 'Lagoa' },
  { name: 'Lagos' },
  { name: 'Lajes das Flores' },
  { name: 'Lajes do Pico' },
  { name: 'Lamego' },
  { name: 'Leiria' },
  { name: 'Lisboa' },
  { name: 'Loulé' },
  { name: 'Loures' },
  { name: 'Lourinhã' },
  { name: 'Lousã' },
  { name: 'Lousada' },
  { name: 'Mação' },
  { name: 'Macedo de Cavaleiros' },
  { name: 'Machico' },
  { name: 'Madalena' },
  { name: 'Mafra' },
  { name: 'Maia' },
  { name: 'Mangualde' },
  { name: 'Manteigas' },
  { name: 'Marco de Canaveses' },
  { name: 'Marinha Grande' },
  { name: 'Marvão' },
  { name: 'Matosinhos' },
  { name: 'Mealhada' },
  { name: 'Meda' },
  { name: 'Melgaço' },
  { name: 'Mértola' },
  { name: 'Mesão Frio' },
  { name: 'Mira' },
  { name: 'Miranda do Corvo' },
  { name: 'Miranda do Douro' },
  { name: 'Mirandela' },
  { name: 'Mogadouro' },
  { name: 'Moimenta da Beira' },
  { name: 'Moita' },
  { name: 'Monção' },
  { name: 'Monchique' },
  { name: 'Mondim de Basto' },
  { name: 'Monforte' },
  { name: 'Montalegre' },
  { name: 'Montemor-o-Novo' },
  { name: 'Montemor-o-Velho' },
  { name: 'Montijo' },
  { name: 'Mora' },
  { name: 'Mortágua' },
  { name: 'Moura' },
  { name: 'Mourão' },
  { name: 'Murça' },
  { name: 'Murtosa' },
  { name: 'Nazaré' },
  { name: 'Nelas' },
  { name: 'Nisa' },
  { name: 'Nordeste' },
  { name: 'Óbidos' },
  { name: 'Odemira' },
  { name: 'Odivelas' },
  { name: 'Oeiras' },
  { name: 'Oleiros' },
  { name: 'Olhão da Restauração' },
  { name: 'Oliveira de Azeméis' },
  { name: 'Oliveira de Frades' },
  { name: 'Oliveira do Bairro' },
  { name: 'Oliveira do Hospital' },
  { name: 'Olivença' },
  { name: 'Ourém' },
  { name: 'Ourique' },
  { name: 'Ovar' },
  { name: 'Paços de Fereira' },
  { name: 'Palmela' },
  { name: 'Pampilhosa da Serra' },
  { name: 'Paredes' },
  { name: 'Paredes de Coura' },
  { name: 'Pedrogão Grande' },
  { name: 'Penacova' },
  { name: 'Penafiel' },
  { name: 'Penalva do Castelo' },
  { name: 'Penamacor' },
  { name: 'Penedono' },
  { name: 'Penela' },
  { name: 'Peniche' },
  { name: 'Peso da Régua' },
  { name: 'Pinhel' },
  { name: 'Pombal' },
  { name: 'Ponta Delgada' },
  { name: 'Ponta do Sol' },
  { name: 'Ponte da Barca' },
  { name: 'Ponte de Lima' },
  { name: 'Ponte de Sor' },
  { name: 'Portalegre' },
  { name: 'Portel' },
  { name: 'Portimão' },
  { name: 'Porto' },
  { name: 'Porto de Mós' },
  { name: 'Porto Moniz' },
  { name: 'Porto Santo' },
  { name: 'Povoação' },
  { name: 'Póvoa de Lanhoso' },
  { name: 'Póvoa de Varzim' },
  { name: 'Proença-a-Nova' },
  { name: 'Redondo' },
  { name: 'Reguengos de Monsaraz' },
  { name: 'Resende' },
  { name: 'Ribeira Brava' },
  { name: 'Ribeira da Pena' },
  { name: 'Ribeira Grande' },
  { name: 'Rio Maior' },
  { name: 'Sabrosa' },
  { name: 'Sabugal' },
  { name: 'Salvaterra de Magos' },
  { name: 'Santa Comba Dão' },
  { name: 'Santa Cruz' },
  { name: 'Santa Cruz da Graciosa' },
  { name: 'Santa Cruz das Flores' },
  { name: 'Santa Maria da Feira' },
  { name: 'Santa Marta de Penaguião' },
  { name: 'Santana' },
  { name: 'Santarém' },
  { name: 'Santiago do Cacém' },
  { name: 'Santo Tirso' },
  { name: 'São Brás de Alportel' },
  { name: 'São João da Madeira' },
  { name: 'São João da Pesqueira' },
  { name: 'São Pedro do Sul' },
  { name: 'São Roque do Pico' },
  { name: 'São Vicente' },
  { name: 'Sardoal' },
  { name: 'Sátão' },
  { name: 'Seia' },
  { name: 'Seixal' },
  { name: 'Sernancelhe' },
  { name: 'Serpa' },
  { name: 'Sertã' },
  { name: 'Sesimbra' },
  { name: 'Setúbal' },
  { name: 'Sever do Vouga' },
  { name: 'Silves' },
  { name: 'Sines' },
  { name: 'Sintra' },
  { name: 'Sobral de Monte Agraço' },
  { name: 'Soure' },
  { name: 'Sousel' },
  { name: 'Tábua' },
  { name: 'Tabuaço' },
  { name: 'Tarouca' },
  { name: 'Tavira' },
  { name: 'Terras de Bouro' },
  { name: 'Tomar' },
  { name: 'Tondela' },
  { name: 'Torre de Moncorvo' },
  { name: 'Torres Novas' },
  { name: 'Torres Vedras' },
  { name: 'Trancoso' },
  { name: 'Trofa' },
  { name: 'Vagos' },
  { name: 'Vale de Cambra' },
  { name: 'Valença' },
  { name: 'Valongo' },
  { name: 'Valpaços' },
  { name: 'Velas' },
  { name: 'Vendas Novas' },
  { name: 'Viana do Alentejo' },
  { name: 'Viana do Castelo' },
  { name: 'Vidigueira' },
  { name: 'Vieira do Minho' },
  { name: 'Vila de Rei' },
  { name: 'Vila do Bispo' },
  { name: 'Vila do Conde' },
  { name: 'Vila do Porto' },
  { name: 'Vila Flor' },
  { name: 'Vila Franca de Xira' },
  { name: 'Vila Franca do Campo' },
  { name: 'Vila Nova da Barquinha' },
  { name: 'Vila Nova de Cerveira' },
  { name: 'Vila Nova de Famalicão' },
  { name: 'Vila Nova de Foz Coa' },
  { name: 'Vila Nova de Gaia' },
  { name: 'Vila Nova de Paiva' },
  { name: 'Vila Nova de Poiares' },
  { name: 'Vila Pouca de Aguiar' },
  { name: 'Vila Praia da Vitória' },
  { name: 'Vila Real' },
  { name: 'Vila Real Santo António' },
  { name: 'Vila Velha de Rodão' },
  { name: 'Vila Verde' },
  { name: 'Vila Viçosa' },
  { name: 'Vimioso' },
  { name: 'Vinhais' },
  { name: 'Viseu' },
  { name: 'Vizela' },
  { name: 'Vouzela' }
]

locations.each do |location_data|
  Location.where(location_data).first_or_create!
end

puts 'seeding courses...'

courses = [
  { name: 'Licenciatura em Engenharia Informática',
    acronym: 'LEI' },
  { name: 'Mestrado em Engenharia Informática',
    acronym: 'MEI' },
  { name: 'Mestrado em Engenharia de Sistemas',
    acronym: 'MES' },
  { name: 'Mestrado em Bioinformática',
    acronym: 'BioInf' },
  { name: 'Doutoramento em Informática',
    acronym: 'PDINF' }
]

courses.each do |course_data|
  Course.where(course_data).first_or_create!
end
